namespace Nulo.WinForms.Control.WordCloudGenerator.TextAnalyses.Blacklist.En {
    public class CommonWords : CommonBlacklist {
        private static readonly string[] s_TopCommonWords = new[] {
            "de",
            "a",
            "o",
            "que",
            "e",
            "do",
            "da",
            "em",
            "um",
            "para",
            "é",
            "com",
            "não",
            "uma",
            "os",
            "no",
            "se",
            "na",
            "por",
            "mais",
            "as",
            "dos",
            "como",
            "mas",
            "foi",
            "ao",
            "ele",
            "das",
            "tem",
            "à",
            "seu",
            "sua",
            "ou",
            "ser",
            "quando",
            "muito",
            "há",
            "nos",
            "já",
            "está",
            "eu",
            "também",
            "só",
            "pelo",
            "pela",
            "até",
            "isso",
            "ela",
            "entre",
            "era",
            "depois",
            "sem",
            "mesmo",
            "aos",
            "ter",
            "seus",
            "quem",
            "nas",
            "me",
            "esse",
            "eles",
            "estão",
            "você",
            "tinha",
            "foram",
            "essa",
            "num",
            "nem",
            "suas",
            "meu",
            "às",
            "minha",
            "têm",
            "numa",
            "pelos",
            "elas",
            "havia",
            "seja",
            "qual",
            "será",
            "nós",
            "tenho",
            "lhe",
            "deles",
            "essas",
            "esses",
            "pelas",
            "este",
            "fosse",
            "dele",
            "tu",
            "te",
            "vocês",
            "vos",
            "lhes",
            "meus",
            "minhas",
            "teu",
            "tua",
            "teus",
            "tuas",
            "nosso",
            "nossa",
            "nossos",
            "nossas",
            "dela",
            "delas",
            "esta",
            "estes",
            "estas",
            "aquele",
            "aquela",
            "aqueles",
            "aquelas",
            "isto",
            "aquilo",
            "estou",
            "está",
            "estamos",
            "estão",
            "estive",
            "esteve",
            "estivemos",
            "estiveram",
            "estava",
            "estávamos",
            "estavam",
            "estivera",
            "estivéramos",
            "esteja",
            "estejamos",
            "estejam",
            "estivesse",
            "estivéssemos",
            "estivessem",
            "estiver",
            "estivermos",
            "estiverem",
            "hei",
            "há",
            "havemos",
            "hão",
            "houve",
            "houvemos",
            "houveram",
            "houvera",
            "houvéramos",
            "haja",
            "hajamos",
            "hajam",
            "houvesse",
            "houvéssemos",
            "houvessem",
            "houver",
            "houvermos",
            "houverem",
            "houverei",
            "houverá",
            "houveremos",
            "houverão",
            "houveria",
            "houveríamos",
            "houveriam",
            "sou",
            "somos",
            "são",
            "era",
            "éramos",
            "eram",
            "fui",
            "foi",
            "fomos",
            "foram",
            "fora",
            "fôramos",
            "seja",
            "sejamos",
            "sejam",
            "fosse",
            "fôssemos",
            "fossem",
            "for",
            "formos",
            "forem",
            "serei",
            "será",
            "seremos",
            "serão",
            "seria",
            "seríamos",
            "seriam",
            "tenho",
            "tem",
            "temos",
            "tém",
            "tinha",
            "tínhamos",
            "tinham",
            "tive",
            "teve",
            "tivemos",
            "tiveram",
            "tivera",
            "tivéramos",
            "tenha",
            "tenhamos",
            "tenham",
            "tivesse",
            "tivéssemos",
            "tivessem",
            "tiver",
            "tivermos",
            "tiverem",
            "terei",
            "terá",
            "teremos",
            "terão",
            "teria",
            "teríamos",
            "teriam",

            "ta",
            "vcs",
            "vc",
            "oi",
            "pq",
            "ai",
            "aí",
            "ja",
            "dá",
            "eh",
            "tá",
            "para",
            "pra",
            "pois",
            "si",
            "etc",
            "muiit",
            "vou",
            "porem",
            "porém",
            "dessa",
            "dessas",
            "desse",
            "desses",
            "desta",
            "destas",
            "deste",
            "deste",
            "destes",
            "pode",
            "pude",
            "podendo",
            "poder",
            "poderia",
            "poderiam",
            "podia",
            "podiam",
            "vendo",
            "ver",
            "vez",
            "vindo",
            "vir",
            "vos",
            "vós",
            "ainda"
        };

        public CommonWords() : base(s_TopCommonWords) { }
    }
}


//namespace Nulo.WinForms.Control.WordCloudGenerator.TextAnalyses.Blacklist.En
//{
//    public class CommonWords : CommonBlacklist
//    {
//        private static readonly string[] s_TopCommonWords =
//            new[]
//            {"about",
//            "after",
//            "again",
//            "air",
//            "all",
//            "along",
//            "also",
//            "an",
//            "and",
//            "another",
//            "any",
//            "are",
//            "around",
//            "as",
//            "at",
//            "away",
//            "back",
//            "be",
//            "because",
//            "been",
//            "before",
//            "below",
//            "between",
//            "both",
//            "but",
//            "by",
//            "came",
//            "can",
//            "come",
//            "could",
//            "day",
//            "did",
//            "different",
//            "do",
//            "does",
//            "don't",
//            "down",
//            "each",
//            "end",
//            "even",
//            "every",
//            "few",
//            "find",
//            "first",
//            "for",
//            "found",
//            "from",
//            "get",
//            "give",
//            "go",
//            "good",
//            "great",
//            "had",
//            "has",
//            "have",
//            "he",
//            "help",
//            "her",
//            "here",
//            "him",
//            "his",
//            "home",
//            "house",
//            "how",
//            "I",
//            "if",
//            "in",
//            "into",
//            "is",
//            "it",
//            "its",
//            "just",
//            "know",
//            "large",
//            "last",
//            "left",
//            "like",
//            "line",
//            "little",
//            "long",
//            "look",
//            "made",
//            "make",
//            "man",
//            "many",
//            "may",
//            "me",
//            "men",
//            "might",
//            "more",
//            "most",
//            "Mr.",
//            "must",
//            "my",
//            "name",
//            "never",
//            "new",
//            "next",
//            "no",
//            "not",
//            "now",
//            "number",
//            "of",
//            "off",
//            "old",
//            "on",
//            "one",
//            "only",
//            "or",
//            "other",
//            "our",
//            "out",
//            "over",
//            "own",
//            "part",
//            "people",
//            "place",
//            "put",
//            "read",
//            "right",
//            "said",
//            "same",
//            "saw",
//            "say",
//            "see",
//            "she",
//            "should",
//            "show",
//            "small",
//            "so",
//            "some",
//            "something",
//            "sound",
//            "still",
//            "such",
//            "take",
//            "tell",
//            "than",
//            "that",
//            "the",
//            "them",
//            "then",
//            "there",
//            "these",
//            "they",
//            "thing",
//            "think",
//            "this",
//            "those",
//            "thought",
//            "three",
//            "through",
//            "time",
//            "to",
//            "together",
//            "too",
//            "two",
//            "under",
//            "up",
//            "us",
//            "use",
//            "very",
//            "want",
//            "water",
//            "way",
//            "we",
//            "well",
//            "went",
//            "were",
//            "what",
//            "when",
//            "where",
//            "which",
//            "while",
//            "who",
//            "why",
//            "will",
//            "with",
//            "word",
//            "work",
//            "world",
//            "would",
//            "write",
//            "year",
//            "you",
//            "your",
//            "was",
//            "able",
//            "above",
//            "across",
//            "add",
//            "against",
//            "ago",
//            "almost",
//            "among",
//            "animal",
//            "answer",
//            "became",
//            "become",
//            "began",
//            "behind",
//            "being",
//            "better",
//            "black",
//            "best",
//            "body",
//            "book",
//            "boy",
//            "brought",
//            "call",
//            "cannot",
//            "car",
//            "certain",
//            "change",
//            "children",
//            "city",
//            "close",
//            "cold",
//            "country",
//            "course",
//            "cut",
//            "didn't",
//            "dog",
//            "done",
//            "door",
//            "draw",
//            "during",
//            "early",
//            "earth",
//            "eat",
//            "enough",
//            "ever",
//            "example",
//            "eye",
//            "face",
//            "family",
//            "far",
//            "father",
//            "feel",
//            "feet",
//            "fire",
//            "fish",
//            "five",
//            "food",
//            "form",
//            "four",
//            "front",
//            "gave",
//            "given",
//            "got",
//            "green",
//            "ground",
//            "group",
//            "grow",
//            "half",
//            "hand",
//            "hard",
//            "heard",
//            "high",
//            "himself",
//            "however",
//            "I'll",
//            "I'm",
//            "idea",
//            "important",
//            "inside",
//            "John",
//            "keep",
//            "kind",
//            "knew",
//            "known",
//            "land",
//            "later",
//            "learn",
//            "let",
//            "letter",
//            "life",
//            "light",
//            "live",
//            "living",
//            "making",
//            "mean",
//            "means",
//            "money",
//            "morning",
//            "mother",
//            "move",
//            "Mrs.",
//            "near",
//            "night",
//            "nothing",
//            "once",
//            "open",
//            "order",
//            "page",
//            "paper",
//            "parts",
//            "perhaps",
//            "picture",
//            "play",
//            "point",
//            "ready",
//            "red",
//            "remember",
//            "rest",
//            "room",
//            "run",
//            "school",
//            "sea",
//            "second",
//            "seen",
//            "sentence",
//            "several",
//            "short",
//            "shown",
//            "since",
//            "six",
//            "slide",
//            "sometime",
//            "soon",
//            "space",
//            "States",
//            "story",
//            "sun",
//            "sure",
//            "table",
//            "though",
//            "today",
//            "told",
//            "took",
//            "top",
//            "toward",
//            "tree",
//            "try",
//            "turn",
//            "United",
//            "until",
//            "upon",
//            "using",
//            "usually",
//            "white",
//            "whole",
//            "wind",
//            "without",
//            "yes",
//            "yet",
//            "young"};

//        public CommonWords()
//            : base(s_TopCommonWords)
//        {

//        }
//    }
//}
